spring.application.name=portfolio

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/portfolio}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Ayush8923}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=zoomgy_super_secret_key_for_jwt_authentication_2026
jwt.expiration=86400000

server.port=${PORT:8080}

